"""Markdown report generator for Apex Debug findings."""

from __future__ import annotations

from pathlib import Path
from typing import Optional

from apex_debug.core.finding import Finding


def generate_report(findings: list[Finding], title: str = "Apex Debug Report") -> str:
    """Generate a Markdown report from findings."""
    parts = [
        f"# {title}\n",
        f"**{len(findings)} issue(s) found**\n",
        "---\n",
    ]

    sev_order = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]

    for sev in sev_order:
        batch = [f for f in findings if f.severity.name == sev]
        if not batch:
            continue

        parts.append(f"## {sev}\n")

        for f in batch:
            sections = [
                f"### {f.title}\n",
                f"- **Severity:** {f.severity.name}",
                f"- **Category:** {f.category}",
                f"- **Location:** `{f.location_str()}`",
                f"- **Confidence:** {f.confidence:.0%}\n",
                f"**Description:** {f.message}\n",
            ]

            if f.snippet:
                sections.extend([
                    "```python",
                    f.snippet.strip(),
                    "```\n",
                ])

            if f.ai_explanation:
                sections.extend([
                    "**AI Explanation:**\n",
                    f"> {f.ai_explanation}\n",
                ])

            if f.ai_fix:
                sections.extend([
                    "**Suggested Fix:**\n",
                    "```diff",
                    f.ai_fix.strip(),
                    "```\n",
                ])

            sections.append("---\n")
            parts.append("\n".join(sections))

    parts.append("*Generated by [Apex Debug](https://apex.debug)*\n")
    return "\n".join(parts)


def save_report(findings: list[Finding], filepath: str, title: Optional[str] = None) -> Path:
    """Save a Markdown report to disk."""
    out = Path(filepath)
    report = generate_report(findings, title or f"Apex Debug — {out.stem}")
    out.write_text(report, encoding="utf-8")
    return out
